//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInfoDB
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanySynonyms = new HashSet<CompanySynonym>();
            this.Jobs = new HashSet<Job>();
            this.JobTemps = new HashSet<JobTemp>();
        }
    
        public string IDCompany { get; set; }
        public string Name { get; set; }
        public string CompanyInfo { get; set; }
        public string ImageLink { get; set; }
         [IgnoreDataMember]
        public virtual ICollection<CompanySynonym> CompanySynonyms { get; set; }
           [IgnoreDataMember]
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<JobTemp> JobTemps { get; set; }
    }
}
