//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInfoDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobDatabaseEntities : DbContext
    {
        public JobDatabaseEntities()
            : base("name=JobDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanySynonym> CompanySynonyms { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobTag> JobTags { get; set; }
        public virtual DbSet<JobTemp> JobTemps { get; set; }
        public virtual DbSet<JobUrl> JobUrls { get; set; }
        public virtual DbSet<JobUrlSource> JobUrlSources { get; set; }
        public virtual DbSet<ProcessState> ProcessStates { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagType> TagTypes { get; set; }
    }
}
