//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInfoDB
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class JobUrl
    {
        public JobUrl()
        {
            this.Jobs = new HashSet<Job>();
            this.JobTemps = new HashSet<JobTemp>();
        }
    
        public string IDJobUrl { get; set; }
        public string JobUrlName { get; set; }
        public string IDProcessState { get; set; }
        public string TimeGet { get; set; }
        public string IDJUSource { get; set; }
       [IgnoreDataMember]
        public virtual ICollection<Job> Jobs { get; set; }
          [IgnoreDataMember]
        public virtual ICollection<JobTemp> JobTemps { get; set; }
        public virtual JobUrlSource JobUrlSource { get; set; }
        public virtual ProcessState ProcessState { get; set; }
    }
}
