//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInfoDB
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class JobUrlSource
    {
        public JobUrlSource()
        {
            this.JobUrls = new HashSet<JobUrl>();
        }
    
        public string IDJUSource { get; set; }
        public string JUSourceName { get; set; }
       [IgnoreDataMember]
        public virtual ICollection<JobUrl> JobUrls { get; set; }
    }
}
