//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInfoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessState
    {
        public ProcessState()
        {
            this.JobTemps = new HashSet<JobTemp>();
            this.JobUrls = new HashSet<JobUrl>();
        }
    
        public string IDProcessState { get; set; }
        public string ProcessStateName { get; set; }
    
        public virtual ICollection<JobTemp> JobTemps { get; set; }
        public virtual ICollection<JobUrl> JobUrls { get; set; }
    }
}
