//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInfoDB
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class Tag
    {
        public Tag()
        {
            this.JobTags = new HashSet<JobTag>();
            this.Tag1 = new HashSet<Tag>();
        }
    
        public string TagID { get; set; }
        public string NameTag { get; set; }
        public string TagParrentID { get; set; }
        public string TagTypeID { get; set; }
       [IgnoreDataMember]
        public virtual ICollection<JobTag> JobTags { get; set; }
          [IgnoreDataMember]
        public virtual TagType TagType { get; set; }
        [IgnoreDataMember]
        public virtual ICollection<Tag> Tag1 { get; set; }
          [IgnoreDataMember]
        public virtual Tag Tag2 { get; set; }
    }
}
