//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInfoDB
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class TagType
    {
        public TagType()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public string TagTypeID { get; set; }
        public string TagTypeName { get; set; }
       [IgnoreDataMember]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
